#!/usr/bin/expect -f

set timeout 60
spawn googlesamples-assistant-pushtotalk --project-id pi-pillbox-ca671 --device-model-id rasp-pillbox-46290 -v
#spawn /bin/bash /home/pi/Assistant-Integration/AsstIntegration -s calendar
expect {
	"*Press Enter to send a new request...*" {
	exec /bin/bash AsstIntegration -s virtmic_config
	send -- "\r"
	exec /bin/bash AsstIntegration -s virtmic_play
	exec /bin/bash AsstIntegration -s virtmic_undo
	exp_continue
	}
	"*microphone_mode: CLOSE_MICROPHONE*" {
	after 2000
	send \x03
	}
	eof {
	exit 0
	}
	timeout {
	exit 100
	}
}
