#!/usr/bin/expect -f

set timeout 60
set script_dir [lindex $argv 0];

spawn googlesamples-assistant-pushtotalk --project-id pi-pillbox-ca671 --device-model-id rasp-pillbox-46290 -v

expect {
	"*Press Enter to send a new request...*" {
	exec /bin/bash $scrip_dir/AsstIntegration -s virtmic_config
	send -- "\r"
	exec /bin/bash $scrip_dir/AsstIntegration -s virtmic_play
	exec /bin/bash $scrip_dir/AsstIntegration -s virtmic_undo
	exp_continue
	}

	"*microphone_mode: CLOSE_MICROPHONE*" {
	after 2000
	send \x03
	}

	eof {
    exit 0
	}

	timeout {
	exit 100
	}
}
